% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={2 exercices Rstudio},
  pdfauthor={Lynda.M},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{2 exercices Rstudio}
\author{Lynda.M}
\date{2022-05-29}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(openintro)}
\FunctionTok{library}\NormalTok{(car)}
\end{Highlighting}
\end{Shaded}

\hypertarget{import-the-.csv-file-to-the-global-environment-its-relative-to-where-you-put-the-employee.csv-for-example-i-put-it-in-desktop-in-the-office}{%
\subsection{import: the .csv file to the global environment (it's
relative to where you put the employee.csv, for example I put it in
desktop (in the
office)}\label{import-the-.csv-file-to-the-global-environment-its-relative-to-where-you-put-the-employee.csv-for-example-i-put-it-in-desktop-in-the-office}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{employee }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"employee.csv"}\NormalTok{, }\ConstantTok{TRUE}\NormalTok{, }\StringTok{","}\NormalTok{)}
\FunctionTok{class}\NormalTok{(employee)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "data.frame"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(employee)}
\end{Highlighting}
\end{Shaded}

\hypertarget{exercise-1}{%
\subsubsection{Exercise 1}\label{exercise-1}}

\#\#\#\#a a. Check that the sample size is n = 71 observations.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(employee)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 71
\end{verbatim}

The number of rows above shows that sample size is 71.

\#\#\#\#b b. Noting Td.d.l. a random variable following a Student's t
law at d.d.l. degrees of freedom, calculate the probability P (T69
\textgreater{} 0) . Comment.

Answer: The formula for calculating probability is pt(q=T,df). Here we
have df=69 as given above so we calculate the probability as

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pt}\NormalTok{(}\DecValTok{0}\NormalTok{,}\AttributeTok{df=}\DecValTok{69}\NormalTok{,}\AttributeTok{lower.tail=}\NormalTok{F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5
\end{verbatim}

The result shows that one sided p value is 0 which shows that there is
50\% chance of getting distribution on positive side of the t-curve.

\#\#\#\#c c.~Find the point q0.8 such that P (T69 \textless{} q0.8) =
0.8 (80\% of the observations are below).

Answer:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pt}\NormalTok{(}\FloatTok{0.8}\NormalTok{,}\AttributeTok{df=}\DecValTok{69}\NormalTok{,}\AttributeTok{lower.tail =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7867717
\end{verbatim}

\#\#\#\#d d.~Find the point t⋆69 such that P (\textbar T69\textbar{} ≥
t⋆69 ) = α where α = 5\%. Answer:

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{pt}\NormalTok{(}\FloatTok{0.69}\NormalTok{,}\DecValTok{69}\NormalTok{,}\AttributeTok{lower.tail =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2462542
\end{verbatim}

\hypertarget{exercice-2}{%
\subsubsection{Exercice 2}\label{exercice-2}}

Consider experience as the explanatory variable and salary as the
explained variable.

donc x= experience (explanatory variable), y= salary (explained
variable).

\#\#\#\#a a. Calculate the mean of each of these variables as well as
their respective standard deviation. \#\#\#\#\#a.1

Answer: La moyenne de la variable expérience est : 5.746479 l'écart type
de la variable expérience est : 3.241333

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(employee}\SpecialCharTok{$}\NormalTok{experience)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.746479
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(employee}\SpecialCharTok{$}\NormalTok{experience)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.241333
\end{verbatim}

Mean value for experience is 5.74 Standard deviation for experience is
3.24.

\#\#\#\#\#a.2

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(employee}\SpecialCharTok{$}\NormalTok{salary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 45141.51
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(employee}\SpecialCharTok{$}\NormalTok{salary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10805.85
\end{verbatim}

La moyenne de la variable salary est : 45141.51 l'écart type de la
variable expérience est : 10805.85

\#\#\#\#b b. Use a scatter plot to represent the relationship between
these two variables and describe the relationship between them.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\FunctionTok{ggplot}\NormalTok{(employee) }\SpecialCharTok{+}
 \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ experience, }\AttributeTok{y =}\NormalTok{ salary) }\SpecialCharTok{+}
 \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{shape =} \StringTok{"circle open"}\NormalTok{, }\AttributeTok{size =} \FloatTok{2.6}\NormalTok{, }\AttributeTok{colour =} \StringTok{"\#461124"}\NormalTok{) }\SpecialCharTok{+}
 \FunctionTok{labs}\NormalTok{(}\AttributeTok{subtitle =} \StringTok{"Relationship between salary and experience"}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{ ggthemes}\SpecialCharTok{::}\FunctionTok{theme\_base}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{2-Exercices-of-stat-by-Rstudio_files/figure-latex/unnamed-chunk-8-1.pdf}
Generally with increase in experience salary also increases according to
the plot. The relationship between two variable is not strictly linear.
In some cases the salary is high even with less experience. The employee
with 10 years of experience have highest salaries in the dataset.

\#\#\#\#c c.~Calculate and interpret their correlation coefficient.
Comment against the scatter plot.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(employee}\SpecialCharTok{$}\NormalTok{experience,employee}\SpecialCharTok{$}\NormalTok{salary,}\AttributeTok{method=}\FunctionTok{c}\NormalTok{(}\StringTok{"pearson"}\NormalTok{, }\StringTok{"kendall"}\NormalTok{, }\StringTok{"spearman"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5515126
\end{verbatim}

Corelation coefficient value is 0.55 between the two variables.
Generally the coefficient value \textgreater{} 0.5 means that two
variables are weakly positive correlated with each other. It can be
observed from the scatter plot as well where with increase of experience
salary increases as well. The scatter plots shows that there are some
cases where salary is not increasing with experience for employee and it
can be an underlying reason for not getting a much value of correlation
coefficient.

\#\#\#\#d d.~Give the equation of the regression line that connects the
two variables and plot it on the scatter plot.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(employee}\SpecialCharTok{$}\NormalTok{experience}\SpecialCharTok{\textasciitilde{}}\NormalTok{employee}\SpecialCharTok{$}\NormalTok{salary,}\AttributeTok{data=}\NormalTok{employee)}
\NormalTok{model}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = employee$experience ~ employee$salary, data = employee)
## 
## Coefficients:
##     (Intercept)  employee$salary  
##      -1.7213787        0.0001654
\end{verbatim}

Answer:

\begin{itemize}
\tightlist
\item
  the estimated regression line equation can be written as follows:
\end{itemize}

salary = -1.7213787 + 0.0001654*experience

The intercept value is negative which means that the

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ employee, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ experience, }\AttributeTok{y =}\NormalTok{ salary)) }\SpecialCharTok{+} \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{stat\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{ ggthemes}\SpecialCharTok{::}\FunctionTok{theme\_base}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{2-Exercices-of-stat-by-Rstudio_files/figure-latex/unnamed-chunk-11-1.pdf}

\#\#\#\#e e. Calculate the standard error Sb1 of the slope b1 of the
regression line.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{deviance}\NormalTok{(model)}\SpecialCharTok{/}\FunctionTok{df.residual}\NormalTok{(model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.723334
\end{verbatim}

standard error \(S_{b1}\) of slope \(b_1\): 2.72 on 69 degrees of
freedom

\#\#\#\#f f.~Deduce the 95\% confidence interval of the slope b1.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{confint}\NormalTok{(model,}\StringTok{\textquotesingle{}employee$salary\textquotesingle{}}\NormalTok{,}\AttributeTok{level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                        2.5 %       97.5 %
## employee$salary 0.0001053392 0.0002255252
\end{verbatim}

\#\#\#\#g g. Test at the 5\% threshold if the slope is significantly
different from 0. Interpret the result.

For this purpose we need to define 2 hypothesis at 5\% sigi=nficance
level which can tested afterwards; \textbf{Null hypothesis H0}: Slope is
significantly different than 0 \textbf{Alternate Hypothesis HA}: Slope
is not significantly different than 0

The result of t-test below shows that p-value is less than 0.05
(significance level) so we reject our null hypothesis.

Since we rejected the null hypothesis, we have sufficient evidence to
say that the true average increase in salary for experience is not zero.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(employee}\SpecialCharTok{$}\NormalTok{experience,employee}\SpecialCharTok{$}\NormalTok{salary,}\AttributeTok{data=}\NormalTok{employee)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  employee$experience and employee$salary
## t = -35.196, df = 70, p-value < 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -47693.46 -42578.06
## sample estimates:
##    mean of x    mean of y 
##     5.746479 45141.507042
\end{verbatim}

\#\#\#\#h h. How much of the variability in wages can be explained by
the fact that some employees have more experience than others?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = employee$experience ~ employee$salary, data = employee)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.1165 -2.0753  0.0411  2.5985  4.3389 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     -1.721e+00  1.398e+00  -1.232    0.222    
## employee$salary  1.654e-04  3.012e-05   5.492 6.21e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.723 on 69 degrees of freedom
## Multiple R-squared:  0.3042, Adjusted R-squared:  0.2941 
## F-statistic: 30.16 on 1 and 69 DF,  p-value: 6.206e-07
\end{verbatim}

The summary of our regression model shows that R2 is 0.29 which means
for 29\% percent of time the salary can be predicted based on the
experience value. Hence 29\% of variability in one can be explained by
the differences in the other variable.

\#\#\#\#i i. What annual salary could be expected from an employee with
8 years of experience? And an employee with 3 years of experience?

We can deduce that from our linear equation of the model. \#\#\#\# For 8
years of experience

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model,}\FunctionTok{data.frame}\NormalTok{(}\StringTok{\textquotesingle{}experience\textquotesingle{}}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{)),}\AttributeTok{interval =} \StringTok{\textquotesingle{}confidence\textquotesingle{}}\NormalTok{,}\AttributeTok{level=}\FloatTok{0.95}\NormalTok{)}\SpecialCharTok{*}\DecValTok{10000}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: 'newdata' had 1 row but variables found have 71 rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(p)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 57464.79
\end{verbatim}

so for an employee with 8 years of experience mean salary of 57464 is
expected.

\hypertarget{for-3-years-of-experience}{%
\paragraph{for 3 years of experience}\label{for-3-years-of-experience}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model,}\AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\DecValTok{3}\NormalTok{))}\SpecialCharTok{*}\DecValTok{10000}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: 'newdata' had 1 row but variables found have 71 rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(p)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 57464.79
\end{verbatim}

so for an employee with 3 years of experience mean salary of 57464 is
expected.

\#\#\#\#j j. Examine the regression conditions based on the residuals.

Extraction des résidus

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(}\FunctionTok{resid}\NormalTok{(model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          1          2          3          4          5          6 
## -0.6333298  2.9246884  2.9994637 -6.1165043 -1.6498201  3.6097430
\end{verbatim}

It is observed that the residuals seem to follow a trend. On time series
data (traditionally ordered chronologically), this could indicate an
auto-correlation of errors (contrary to the independence hypothesis),
and therefore of condition not taken into account (ex: age, training,
etc.) .

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res}\OtherTok{\textless{}{-}}\FunctionTok{resid}\NormalTok{(model)}
\FunctionTok{plot}\NormalTok{(res,}\AttributeTok{main=}\StringTok{"Résidus"}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{abline}\NormalTok{(}\AttributeTok{h=}\DecValTok{0}\NormalTok{,}\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{2-Exercices-of-stat-by-Rstudio_files/figure-latex/unnamed-chunk-19-1.pdf}

\begin{verbatim}
## integer(0)
\end{verbatim}

\hypertarget{k}{%
\paragraph{k}\label{k}}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Create employee\_f a base that includes all employees and employee\_m
  the rest of the sample. Calculate the slope of the regression in each
  subgroup and comment.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#subtracting 1st id column}
\NormalTok{p }\OtherTok{\textless{}{-}}\NormalTok{ employee[,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{]}

\CommentTok{\# creating a dataframe for female employee}
\NormalTok{employee\_f }\OtherTok{\textless{}{-}}\NormalTok{ p }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(gender}\SpecialCharTok{==}\DecValTok{0}\NormalTok{)}

\CommentTok{\#creating a dataframe for male employee}
\NormalTok{employee\_m }\OtherTok{\textless{}{-}}\NormalTok{ p }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(gender}\SpecialCharTok{==}\DecValTok{1}\NormalTok{)}

\CommentTok{\#fitting regression model on female employee}
\NormalTok{model\_f }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(employee\_f}\SpecialCharTok{$}\NormalTok{experience}\SpecialCharTok{\textasciitilde{}}\NormalTok{employee\_f}\SpecialCharTok{$}\NormalTok{salary,}\AttributeTok{data=}\NormalTok{employee\_f)}

\CommentTok{\#fitting regression model on male employee}
\NormalTok{model\_m }\OtherTok{\textless{}{-}}  \FunctionTok{lm}\NormalTok{(employee\_m}\SpecialCharTok{$}\NormalTok{experience}\SpecialCharTok{\textasciitilde{}}\NormalTok{employee\_m}\SpecialCharTok{$}\NormalTok{salary,}\AttributeTok{data=}\NormalTok{employee\_m)}

\CommentTok{\# slope of regression for female subgroup}

\NormalTok{model\_f}\SpecialCharTok{$}\NormalTok{coef[}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## employee_f$salary 
##      0.0001175642
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# slope of regression for male subgroup}
\NormalTok{model\_m}\SpecialCharTok{$}\NormalTok{coef[}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## employee_m$salary 
##      0.0002276517
\end{verbatim}

The slope of regression for female subgroup is
\ensuremath{1.175642\times 10^{-4}} and the slope of regression for male
subgroup is \ensuremath{2.276517\times 10^{-4}}.

\end{document}
